version: "3.9"
services:
  orquestrador:
    build: ../orquestrador/
    volumes:
      - .:/usr/app
    ports:
      - 8001:8001
    environment: 
      - HOST_REDIS=redis
      - PORT_REDIS=6379
      - URL_RABBIT_MQ=amqp://guest:guest@rabbit-mq/
      - HOST_JAEGER=jaeger-all-in-one
      - PORT_JAEGER=6831
      - PROXY_CONTA=http://conta-service:8003/
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger-all-in-one:5778
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=jaeger-all-in-one
    depends_on: 
      - redis
      - rabbit-mq
      - jaeger-all-in-one
    networks:
      - trader-network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 800M
        reservations:
          cpus: '0.25'
          memory: 800M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s 

  ordem-service:
    build: ../ordem-service/
    volumes:
      - .:/usr/app
    ports:
      - 8000:8000
    environment: 
      - HOST_REDIS=redis
      - PORT_REDIS=6379
      - URL_RABBIT_MQ=amqp://guest:guest@rabbit-mq/
      - HOST_JAEGER=jaeger-all-in-one
      - PORT_JAEGER=6831
      - PROXY_CONTA=http://conta-service:8003/
    depends_on: 
      - redis
      - rabbit-mq
      - conta-service
      - jaeger-all-in-one      
    networks:
      - trader-network
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 800M
        reservations:
          cpus: '0.25'
          memory: 800M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s 
  init-service:
    build: ../init-ordem/
    volumes:
      - .:/usr/app
    ports:
      - 8002:8002
    environment: 
      - HOST_REDIS=redis
      - PORT_REDIS=6379
      - URL_RABBIT_MQ=amqp://guest:guest@rabbit-mq/
      - HOST_JAEGER=jaeger-all-in-one
      - PORT_JAEGER=6831
    depends_on: 
      - redis
      - rabbit-mq
      - jaeger-all-in-one      
    networks:
      - trader-network
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: '0.50'
          memory: 800M
        reservations:
          cpus: '0.25'
          memory: 800M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s 
  conta-service:
    build: ../conta-service/
    volumes:
      - .:/usr/app
    ports:
      - 8003:8003
    environment: 
      - HOST_REDIS=redis
      - PORT_REDIS=6379
      - URL_RABBIT_MQ=amqp://guest:guest@rabbit-mq/
      - HOST_JAEGER=jaeger-all-in-one
      - PORT_JAEGER=6831
    depends_on: 
      - redis
      - rabbit-mq
      - jaeger-all-in-one      
    networks:
      - trader-network
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 800M
        reservations:
          cpus: '0.25'
          memory: 800M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s 
  jaeger-all-in-one:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 14268
      - 14250
      - 5775:5775/udp
      - 6832:6832/udp
      - 5778:5778
      - 14268:14268
      - 9411:9411     
    networks:
      - trader-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - trader-network

  redis:
    image: redislabs/redismod
    ports:
    - 6379:6379
    volumes:
      - redis_data:/data/redis
    restart: always
    networks:
      - trader-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - trader-network  

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    networks:
      - trader-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ../grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ../grafana/config.monitoring
    networks:
      - trader-network
    restart: always

volumes:
  redis_data: {}      
  grafana_data: {}

networks:
  trader-network:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 