scrape_configs:
  - job_name: 'conta-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['conta-service:8003']
  - job_name: 'init-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['init-service:8002']
  - job_name: 'ordem-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['ordem-service:8000']
  - job_name: 'orquestrador'
    scrape_interval: 10s
    static_configs:
      - targets: ['orquestrador:8001']
  - job_name: rabbit-mq
    scrape_interval: 60s
    static_configs:
      - targets: ['rabbit-mq:15692'] 